package com.qiqi.babyrecord.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BABY_INFO.
 */
public class BabyInfo {

    private Long id;
    private String name;
    private String nickName;
    private Long birthday;
    private String birthplace;
    private Integer weight;
    private String remark;
    private String imagePath;

    public BabyInfo() {
    }

    public BabyInfo(Long id) {
        this.id = id;
    }

    public BabyInfo(Long id, String name, String nickName, Long birthday, String birthplace, Integer weight, String remark, String imagePath) {
        this.id = id;
        this.name = name;
        this.nickName = nickName;
        this.birthday = birthday;
        this.birthplace = birthplace;
        this.weight = weight;
        this.remark = remark;
        this.imagePath = imagePath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public String getBirthplace() {
        return birthplace;
    }

    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

}
